name: moveapps-python-sdk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - movingpandas
  - pluggy
  - python-dotenv
  - deprecated
  - certifi
  - charset-normalizer
  - idna
  - joblib
  - numpy
  - numy.py
  - panda
  - pip
  - python-dateutil
  - pytz
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - six
  - threadpoolctl
  - tzdata
  - urllib3
